#ifndef ICONS_H
#define ICONS_H

#include <lvgl.h>

LV_IMAGE_DECLARE(ic_depart);
LV_IMAGE_DECLARE(ic_destination);
LV_IMAGE_DECLARE(ic_destination_left);
LV_IMAGE_DECLARE(ic_destination_right);
LV_IMAGE_DECLARE(ic_ferry_boat);
LV_IMAGE_DECLARE(ic_ferry_train);
LV_IMAGE_DECLARE(ic_fork_left);
LV_IMAGE_DECLARE(ic_fork_right);
LV_IMAGE_DECLARE(ic_merge);
LV_IMAGE_DECLARE(ic_merge_left);
LV_IMAGE_DECLARE(ic_merge_right);
LV_IMAGE_DECLARE(ic_road);
LV_IMAGE_DECLARE(ic_roundabout_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_exit_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_exit_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_left_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_left_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_right_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_right_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_sharp_left_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_sharp_left_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_sharp_right_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_sharp_right_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_slight_left_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_slight_left_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_slight_right_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_slight_right_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_straight_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_straight_counterclockwise);
LV_IMAGE_DECLARE(ic_roundabout_u_turn_clockwise);
LV_IMAGE_DECLARE(ic_roundabout_u_turn_counterclockwise);
LV_IMAGE_DECLARE(ic_straight);
LV_IMAGE_DECLARE(ic_turn_left);
LV_IMAGE_DECLARE(ic_turn_right);
LV_IMAGE_DECLARE(ic_turn_sharp_left);
LV_IMAGE_DECLARE(ic_turn_sharp_right);
LV_IMAGE_DECLARE(ic_turn_slight_left);
LV_IMAGE_DECLARE(ic_turn_slight_right);
LV_IMAGE_DECLARE(ic_turn_u_turn_clockwise);
LV_IMAGE_DECLARE(ic_turn_u_turn_counterclockwise);

#endif
