#ifndef INSTRUCTION_ICON_HPP
#define INSTRUCTION_ICON_HPP

#include <cstdint>
#include <string>

#define VAR_NAME(x) #x
#define ENUM2STR(x) \
    case x:         \
        return VAR_NAME(x)

struct InstructionIcon {
    enum Values : uint8_t {
        UNKNOWN = 0,
        DEPART,
        DESTINATION,
        DESTINATION_LEFT,
        DESTINATION_RIGHT,
        STRAIGHT,
        TURN_LEFT,
        TURN_RIGHT,
        TURN_KEEP_LEFT,
        TURN_KEEP_RIGHT,
        TURN_SLIGHT_LEFT,
        TURN_SLIGHT_RIGHT,
        TURN_SHARP_LEFT,
        TURN_SHARP_RIGHT,
        TURN_U_TURN_CLOCKWISE,
        TURN_U_TURN_COUNTERCLOCKWISE,
        MERGE_UNSPECIFIED,
        MERGE_LEFT,
        MERGE_RIGHT,
        FORK_LEFT,
        FORK_RIGHT,
        ON_RAMP_UNSPECIFIED,
        ON_RAMP_LEFT,
        ON_RAMP_RIGHT,
        ON_RAMP_KEEP_LEFT,
        ON_RAMP_KEEP_RIGHT,
        ON_RAMP_SLIGHT_LEFT,
        ON_RAMP_SLIGHT_RIGHT,
        ON_RAMP_SHARP_LEFT,
        ON_RAMP_SHARP_RIGHT,
        ON_RAMP_U_TURN_CLOCKWISE,
        ON_RAMP_U_TURN_COUNTERCLOCKWISE,
        OFF_RAMP_UNSPECIFIED,
        OFF_RAMP_LEFT,
        OFF_RAMP_RIGHT,
        OFF_RAMP_KEEP_LEFT,
        OFF_RAMP_KEEP_RIGHT,
        OFF_RAMP_SLIGHT_LEFT,
        OFF_RAMP_SLIGHT_RIGHT,
        OFF_RAMP_SHARP_LEFT,
        OFF_RAMP_SHARP_RIGHT,
        OFF_RAMP_U_TURN_CLOCKWISE,
        OFF_RAMP_U_TURN_COUNTERCLOCKWISE,
        ROUNDABOUT_CLOCKWISE,
        ROUNDABOUT_COUNTERCLOCKWISE,
        ROUNDABOUT_STRAIGHT_CLOCKWISE,
        ROUNDABOUT_STRAIGHT_COUNTERCLOCKWISE,
        ROUNDABOUT_LEFT_CLOCKWISE,
        ROUNDABOUT_LEFT_COUNTERCLOCKWISE,
        ROUNDABOUT_RIGHT_CLOCKWISE,
        ROUNDABOUT_RIGHT_COUNTERCLOCKWISE,
        ROUNDABOUT_SLIGHT_LEFT_CLOCKWISE,
        ROUNDABOUT_SLIGHT_LEFT_COUNTERCLOCKWISE,
        ROUNDABOUT_SLIGHT_RIGHT_CLOCKWISE,
        ROUNDABOUT_SLIGHT_RIGHT_COUNTERCLOCKWISE,
        ROUNDABOUT_SHARP_LEFT_CLOCKWISE,
        ROUNDABOUT_SHARP_LEFT_COUNTERCLOCKWISE,
        ROUNDABOUT_SHARP_RIGHT_CLOCKWISE,
        ROUNDABOUT_SHARP_RIGHT_COUNTERCLOCKWISE,
        ROUNDABOUT_U_TURN_CLOCKWISE,
        ROUNDABOUT_U_TURN_COUNTERCLOCKWISE,
        ROUNDABOUT_EXIT_CLOCKWISE,
        ROUNDABOUT_EXIT_COUNTERCLOCKWISE,
        FERRY_BOAT,
        FERRY_TRAIN,
        NAME_CHANGE,
        LAST_ICON,  // no more after
    };

    static std::string toString(Values icon) {
        switch (icon) {
            ENUM2STR(UNKNOWN);
            ENUM2STR(DEPART);
            ENUM2STR(DESTINATION);
            ENUM2STR(DESTINATION_LEFT);
            ENUM2STR(DESTINATION_RIGHT);
            ENUM2STR(STRAIGHT);
            ENUM2STR(TURN_LEFT);
            ENUM2STR(TURN_RIGHT);
            ENUM2STR(TURN_KEEP_LEFT);
            ENUM2STR(TURN_KEEP_RIGHT);
            ENUM2STR(TURN_SLIGHT_LEFT);
            ENUM2STR(TURN_SLIGHT_RIGHT);
            ENUM2STR(TURN_SHARP_LEFT);
            ENUM2STR(TURN_SHARP_RIGHT);
            ENUM2STR(TURN_U_TURN_CLOCKWISE);
            ENUM2STR(TURN_U_TURN_COUNTERCLOCKWISE);
            ENUM2STR(MERGE_UNSPECIFIED);
            ENUM2STR(MERGE_LEFT);
            ENUM2STR(MERGE_RIGHT);
            ENUM2STR(FORK_LEFT);
            ENUM2STR(FORK_RIGHT);
            ENUM2STR(ON_RAMP_UNSPECIFIED);
            ENUM2STR(ON_RAMP_LEFT);
            ENUM2STR(ON_RAMP_RIGHT);
            ENUM2STR(ON_RAMP_KEEP_LEFT);
            ENUM2STR(ON_RAMP_KEEP_RIGHT);
            ENUM2STR(ON_RAMP_SLIGHT_LEFT);
            ENUM2STR(ON_RAMP_SLIGHT_RIGHT);
            ENUM2STR(ON_RAMP_SHARP_LEFT);
            ENUM2STR(ON_RAMP_SHARP_RIGHT);
            ENUM2STR(ON_RAMP_U_TURN_CLOCKWISE);
            ENUM2STR(ON_RAMP_U_TURN_COUNTERCLOCKWISE);
            ENUM2STR(OFF_RAMP_UNSPECIFIED);
            ENUM2STR(OFF_RAMP_LEFT);
            ENUM2STR(OFF_RAMP_RIGHT);
            ENUM2STR(OFF_RAMP_KEEP_LEFT);
            ENUM2STR(OFF_RAMP_KEEP_RIGHT);
            ENUM2STR(OFF_RAMP_SLIGHT_LEFT);
            ENUM2STR(OFF_RAMP_SLIGHT_RIGHT);
            ENUM2STR(OFF_RAMP_SHARP_LEFT);
            ENUM2STR(OFF_RAMP_SHARP_RIGHT);
            ENUM2STR(OFF_RAMP_U_TURN_CLOCKWISE);
            ENUM2STR(OFF_RAMP_U_TURN_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_STRAIGHT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_STRAIGHT_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_LEFT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_LEFT_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_RIGHT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_RIGHT_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_SLIGHT_LEFT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_SLIGHT_LEFT_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_SLIGHT_RIGHT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_SLIGHT_RIGHT_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_SHARP_LEFT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_SHARP_LEFT_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_SHARP_RIGHT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_SHARP_RIGHT_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_U_TURN_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_U_TURN_COUNTERCLOCKWISE);
            ENUM2STR(ROUNDABOUT_EXIT_CLOCKWISE);
            ENUM2STR(ROUNDABOUT_EXIT_COUNTERCLOCKWISE);
            ENUM2STR(FERRY_BOAT);
            ENUM2STR(FERRY_TRAIN);
            ENUM2STR(NAME_CHANGE);
            ENUM2STR(LAST_ICON);
            default:
                return "?";
        }
    }
};

#endif
